Fix test failures from mix upgrade
I was seeing the following test failures

    1) test errors with an unknown version (Mix.Tasks.PhxDiff.Gen.SampleTest)
    Error:      test/mix/tasks/phx_diff.gen.sample_test.exs:59
        ** (RuntimeError) error occurred while installing phx_new

        Resolving Hex dependencies...
        #Incompatibility<#Term<your app>, cause: {:conflict, #Incompatibility<#Term<phx_new 0.1.10>, cause: :no_versions>, #Incompatibility<#Term<your app>, #Term<not phx_new 0.1.10>, cause: :dependency>}>
        Resolution completed in 0.038s
        Because "your app" depends on "phx_new 0.1.10" which doesn't match any versions, version solving failed.
        ** (Mix) Hex dependency resolution failed